export const partnersData = [
    { src: "/images/logos/layers.svg", alt: "layers logo", name: "Layers" },
    { src: "/images/logos/sisyphus.svg", alt: "sisyphus logo", name: "Sisyphus" },
    { src: "/images/logos/circooles.svg", alt: "circooles logo", name: "Circooles" },
    { src: "/images/logos/catalog.svg", alt: "catalog logo", name: "Catalog" },
    { src: "/images/logos/quotient.svg", alt: "quotient logo", name: "Quotient" },
  ];

  export const cardData = [
    {
      id: 1,
      imageSrc: "/images/projects/art1.svg",
      price: "$ 2800.00",
    },
    {
      id: 2,
      imageSrc: "/images/projects/art2.svg",
      price: "$ 1500.00",
    },
  ];

  export const projectsData = [
    {
      id: 1,
      title: "Floral Design",
      description: "Elegant floral tattoo for nature lovers.",
      img: "/images/projects/art1.svg",
      link: "https://andrei-design.ro",
    },
    {
      id: 2,
      title: "Geometric Ink",
      description: "Bold geometric shapes for a modern look.",
      img: "/images/projects/proj2.jpeg",
      link: "https://andrei-design.ro",
    },
    {
      id: 3,
      title: "Animal Spirit",
      description: "Express your spirit with animal motifs.",
      img: "/images/projects/art2.svg",
      link: "https://andrei-design.ro",
    },
    {
      id: 4,
      title: "Minimal Art",
      description: "Subtle, minimalist lines for timeless style.",
      img: "/images/projects/proj1.jpeg",
      link: "https://andrei-design.ro",
    },
  ];
  
  export const allprojectsData = [
    {
      date: "8 Jul 2023",
      category: "Tattoo Tips",
      title: "Transform Your Phone into a Tattoo Design Companion",
      description: "Discover ways to use your phone as a tool for creating and refining tattoo designs.",
      imageUrl: "/images/projects/art1.svg",
      clientUrl: "https://andrei-design.ro",
      isVisible: true,
    },
    {
      date: "15 Aug 2023",
      category: "Tattoo Education",
      title: "Tattoo Design Techniques for High-Impact Art",
      description: "Explore techniques to create memorable, impactful tattoos that clients love.",
      imageUrl: "/images/projects/proj2.jpeg",
      clientUrl: "https://andrei-design.ro",
      isVisible: true,
    },
    {
      date: "30 Sep 2023",
      category: "Inspiration",
      title: "Nature-Inspired Tattoos: Bringing the Outdoors to Skin",
      description: "A look at how natural elements like flora and fauna inspire beautiful tattoos.",
      imageUrl: "/images/projects/proj1.jpeg",
      clientUrl: "/images/projects/art2.svg",
      isVisible: true,
    },
    {
      date: "10 Oct 2023",
      category: "Tattoo Aftercare",
      title: "Tattoo Healing 101: What Every Client Should Know",
      description: "An essential guide to aftercare practices for lasting tattoo quality.",
      imageUrl: "/images/projects/proj1.jpeg",
      clientUrl: "https://andrei-design.ro",
      isVisible: true,
    },
    {
      date: "20 Oct 2023",
      category: "Art Styles",
      title: "Exploring Geometric Tattoos: Symmetry in Skin Art",
      description: "Delve into the intricate world of geometric tattoos and why they're popular.",
      imageUrl: "/images/projects/proj2.jpeg",
      clientUrl: "https://andrei-design.ro",
      isVisible: true,
    },
    {
      date: "1 Nov 2023",
      category: "Tattoo Trends",
      title: "Minimalist Tattoos: Why Less is More",
      description: "A guide to minimalist tattoo designs and how to make a bold statement with simplicity.",
      imageUrl: "/images/projects/art1.svg",
      clientUrl: "https://andrei-design.ro",
      isVisible: true,
    },
    {
      date: "5 Nov 2023",
      category: "Client Stories",
      title: "From Idea to Ink: A Client's Journey",
      description: "Follow a real client’s journey from concept to completed tattoo.",
      imageUrl: "/images/projects/art2.svg",
      clientUrl: "https://andrei-design.ro",
      isVisible: true,
    },
    {
      date: "12 Nov 2023",
      category: "Inspiration",
      title: "Tattooing Cultural Symbols: Respectful Design Practices",
      description: "Learn how to incorporate cultural symbols respectfully in tattoo design.",
      imageUrl: "tattoo-assets/images/blog/design-tip6.png",
      clientUrl: "https://andrei-design.ro",
      isVisible: true,
    },
    {
      date: "18 Nov 2023",
      category: "Tattoo Tips",
      title: "Best Practices for Long-Lasting Color Tattoos",
      description: "Tips for vibrant, lasting colors in tattoo designs.",
      imageUrl: "tattoo-assets/images/blog/color-tips1.png",
      clientUrl: "https://andrei-design.ro",
      isVisible: true,
    },
    {
      date: "25 Nov 2023",
      category: "Tattoo Tools",
      title: "Digital Tools Every Tattoo Artist Should Know",
      description: "A look at the best digital tools for sketching and refining tattoo designs.",
      imageUrl: "tattoo-assets/images/blog/tools-tip1.png",
      clientUrl: "https://andrei-design.ro",
      isVisible: true,
    },
    {
      date: "2 Dec 2023",
      category: "Art Styles",
      title: "Traditional vs. Neo-Traditional Tattoos: What's the Difference?",
      description: "Comparing two popular styles and what makes each unique.",
      imageUrl: "tattoo-assets/images/blog/style-tip1.png",
      clientUrl: "https://andrei-design.ro",
      isVisible: true,
    },
    {
      date: "10 Dec 2023",
      category: "Tattoo Techniques",
      title: "Shading Techniques for Realistic Tattoos",
      description: "Mastering shading techniques to add realism to tattoo art.",
      imageUrl: "tattoo-assets/images/blog/shading-tip1.png",
      clientUrl: "https://andrei-design.ro",
      isVisible: true,
    },
    {
      date: "18 Dec 2023",
      category: "Tattoo Tips",
      title: "Pain Management Tips for Tattoo Clients",
      description: "Advice for clients to handle pain during tattoo sessions.",
      imageUrl: "tattoo-assets/images/blog/pain-management1.png",
      clientUrl: "https://andrei-design.ro",
      isVisible: true,
    },
  ];
  